vars: 
  cors-allowed-origins: ${CORS_ALLOWED_ORIGINS:*}
  gmail-username: ${GMAIL_USERNAME:}
  gmail-password: ${GMAIL_PASSWORD:}

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${vars.gmail-username}
    password: ${vars.gmail-password}
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls.enable: true
